name: Maven Package and Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        server-id: github
        settings-path: ${{ github.workspace }}
        java-package: jdk
        overwrite-settings: true
    
    - name: Set up Maven 3.9.2
      uses: actions/setup-java@v4
      with:
        maven-version: '3.9.2'
        
    - name: Bump version
      run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}-SNAPSHOT

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest
