name: Maven Package and Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    
    
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build --build-arg VERSION_NUM=${{ github.run_number }}  -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest

    - name: ssh connect to deploy
      run: ssh -i ${{ secrets.SSH_KEY }} ubuntu@31.26.27.195

    - name: instal dependensies
      run: sudo apt install docker.io -y

#    - name: remove and stop  container
#      run: sudo docker stop hellow && sudo dokcer rm hellow 
     
    - name: run the docker 
      run: yes | docker run --pull=always --name hellow ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest
 

